"""Database-backed optimization action audit and rollback service."""

from __future__ import annotations

import json
import uuid
from datetime import datetime, timezone
from decimal import Decimal
from typing import Any, Optional

from fastapi import HTTPException

from app.db import fetch_all, fetch_one, get_db_connection, is_db_configured
from app.services.agent_log_service import create_agent_log
from app.services.guardrail_service import get_guardrails
from mock_data import ACTIONS

SUMMARY_STATUSES = ["Generated", "Approved", "Executed", "Rejected", "Pending Review", "Rolled Back"]
SORT_COLUMNS = {
    "created_at": "o.created_at",
    "confidence_score": "o.confidence_score",
    "expected_impact_pct": "o.expected_impact_pct",
    "actual_impact_pct": "o.actual_impact_pct",
    "status": "o.status",
    "risk_level": "o.risk_level",
}
DEFAULT_AGENTS = ["Data Scout", "Pattern Miner", "Recommendation Engine", "Risk Guardrail", "Action Executor"]

_fallback_events: list[dict[str, Any]] = []
_fallback_actions = [dict(item) for item in ACTIONS]


def now_iso() -> str:
    return datetime.now(timezone.utc).isoformat()


def number(value: Any) -> float:
    if value is None:
        return 0.0
    if isinstance(value, Decimal):
        return float(value)
    return float(value)


def iso(value: Any) -> Optional[str]:
    if value is None:
        return None
    if hasattr(value, "isoformat"):
        return value.isoformat()
    return str(value)


def parse_json(value: Any, fallback: Any) -> Any:
    if value is None:
        return fallback
    if isinstance(value, (list, dict)):
        return value
    try:
        return json.loads(value)
    except (TypeError, ValueError):
        return fallback


def normalized_status(value: Any) -> str:
    raw = str(value or "Generated").strip().replace("_", " ")
    mapping = {
        "generated": "Generated",
        "pending": "Pending Review",
        "pending review": "Pending Review",
        "approved": "Approved",
        "executed": "Executed",
        "rejected": "Rejected",
        "rolled back": "Rolled Back",
        "rolledback": "Rolled Back",
    }
    return mapping.get(raw.lower(), raw.title())


def action_item(row: dict[str, Any]) -> dict[str, Any]:
    evidence = parse_json(row.get("evidence_refs"), [])
    if not isinstance(evidence, list):
        evidence = [str(evidence)]
    status = normalized_status(row.get("status"))
    return {
        "optimization_id": row.get("optimization_id") or row.get("id"),
        "client_id": row.get("client_id") or row.get("recommendation_id") or "demo-client",
        "brand_name": row.get("brand_name") or row.get("client_name") or "Demo Brand",
        "brand_category": row.get("brand_category"),
        "created_at": iso(row.get("created_at") or row.get("executed_at")) or now_iso(),
        "agent_name": row.get("agent_name") or ("Action Executor" if status in {"Executed", "Rolled Back"} else "Recommendation Engine"),
        "action_type": row.get("action_type") or row.get("type") or row.get("title") or "Optimization",
        "target_platform": row.get("target_platform") or row.get("platform") or infer_platform(row),
        "target_campaign_id": row.get("target_campaign_id") or row.get("campaign_id"),
        "campaign_name": row.get("campaign_name") or row.get("target_campaign_id") or "Campaign configuration",
        "reason": row.get("reason") or row.get("title") or row.get("rollback_reason") or "Optimization action generated by WasteNot.",
        "expected_impact_pct": number(row.get("expected_impact_pct", 0.08)),
        "confidence_score": number(row.get("confidence_score", row.get("confidence", 0.78))),
        "risk_level": str(row.get("risk_level") or row.get("risk") or "Medium").capitalize(),
        "status": status,
        "approved_by": row.get("approved_by") or ("human_ops" if status in {"Approved", "Executed", "Rolled Back"} else None),
        "actual_impact_pct": number(row.get("actual_impact_pct", 0)) if row.get("actual_impact_pct") is not None else None,
        "rollback_flag": bool(row.get("rollback_flag") or status == "Rolled Back" or row.get("rollback_status") == "rolled_back"),
        "evidence_refs": evidence,
        "recommendation_id": row.get("recommendation_id"),
    }


def infer_platform(row: dict[str, Any]) -> str:
    text = " ".join(str(row.get(key, "")) for key in ("title", "type", "reason")).lower()
    if "google" in text or "shopping" in text or "search" in text:
        return "Google"
    return "Meta"


def mock_action_rows() -> list[dict[str, Any]]:
    return [action_item(item) for item in _fallback_actions]


def get_summary() -> dict[str, Any]:
    if is_db_configured():
        try:
            row = fetch_one(
                """
                SELECT COUNT(*) AS total_actions,
                       COUNT(*) FILTER (WHERE lower(status) = 'generated') AS generated,
                       COUNT(*) FILTER (WHERE lower(status) = 'approved') AS approved,
                       COUNT(*) FILTER (WHERE lower(status) = 'executed') AS executed,
                       COUNT(*) FILTER (WHERE lower(status) = 'rejected') AS rejected,
                       COUNT(*) FILTER (WHERE lower(status) IN ('pending review', 'pending_review', 'pending')) AS pending_review,
                       COUNT(*) FILTER (WHERE rollback_flag IS TRUE OR lower(status) IN ('rolled back', 'rolled_back')) AS rolled_back,
                       AVG(confidence_score) AS avg_confidence,
                       AVG(expected_impact_pct) AS estimated_avg_impact_pct,
                       AVG(actual_impact_pct) FILTER (WHERE actual_impact_pct IS NOT NULL) AS actual_avg_impact_pct
                FROM optimization_history
                """
            ) or {}
            return summary_payload(row, "database")
        except Exception:
            pass
    items = mock_action_rows()
    row = {"total_actions": len(items)}
    for status in SUMMARY_STATUSES:
        row[status.lower().replace(" ", "_")] = len([item for item in items if item["status"] == status])
    row["rolled_back"] = len([item for item in items if item["rollback_flag"] or item["status"] == "Rolled Back"])
    row["avg_confidence"] = average([item["confidence_score"] for item in items])
    row["estimated_avg_impact_pct"] = average([item["expected_impact_pct"] for item in items])
    row["actual_avg_impact_pct"] = average([item["actual_impact_pct"] for item in items if item["actual_impact_pct"] is not None])
    return summary_payload(row, "mock")


def summary_payload(row: dict[str, Any], source: str) -> dict[str, Any]:
    total = int(row.get("total_actions") or 0)
    rolled_back = int(row.get("rolled_back") or 0)
    return {
        "total_actions": total,
        "generated": int(row.get("generated") or 0),
        "approved": int(row.get("approved") or 0),
        "executed": int(row.get("executed") or 0),
        "rejected": int(row.get("rejected") or 0),
        "pending_review": int(row.get("pending_review") or 0),
        "rolled_back": rolled_back,
        "rollback_rate": rolled_back / total if total else 0,
        "avg_confidence": number(row.get("avg_confidence")),
        "estimated_avg_impact_pct": number(row.get("estimated_avg_impact_pct")),
        "actual_avg_impact_pct": number(row.get("actual_avg_impact_pct")),
        "source": source,
    }


def average(values: list[float]) -> float:
    return sum(values) / len(values) if values else 0


def filters_sql(filters: dict[str, Any]) -> tuple[str, list[Any]]:
    clauses: list[str] = []
    params: list[Any] = []
    mapping = {
        "client_id": "o.client_id = %s",
        "platform": "o.target_platform = %s",
        "risk_level": "o.risk_level = %s",
        "status": "o.status = %s",
        "agent_name": "o.agent_name = %s",
    }
    for key, clause in mapping.items():
        if filters.get(key):
            clauses.append(clause)
            params.append(filters[key])
    if filters.get("rollback_flag") is not None:
        clauses.append("o.rollback_flag = %s")
        params.append(bool(filters["rollback_flag"]))
    if filters.get("search"):
        clauses.append(
            "(o.action_type ILIKE %s OR o.reason ILIKE %s OR c.brand_name ILIKE %s OR o.target_platform ILIKE %s OR o.target_campaign_id ILIKE %s OR o.agent_name ILIKE %s OR o.approved_by ILIKE %s)"
        )
        params.extend([f"%{filters['search']}%"] * 7)
    return (f"WHERE {' AND '.join(clauses)}" if clauses else "", params)


def list_actions(filters: dict[str, Any]) -> dict[str, Any]:
    limit = int(filters.get("limit") or 50)
    offset = int(filters.get("offset") or 0)
    if is_db_configured():
        try:
            where, params = filters_sql(filters)
            sort_by = filters.get("sort_by") if filters.get("sort_by") in SORT_COLUMNS else "created_at"
            sort_dir = "ASC" if str(filters.get("sort_dir")).lower() == "asc" else "DESC"
            rows = fetch_all(
                f"""
                SELECT o.*, c.brand_name, c.brand_category, s.campaign_name
                FROM optimization_history o
                LEFT JOIN clients c ON c.client_id = o.client_id
                LEFT JOIN ad_campaign_settings s ON s.campaign_id = o.target_campaign_id
                {where}
                ORDER BY {SORT_COLUMNS[sort_by]} {sort_dir} NULLS LAST
                LIMIT %s OFFSET %s
                """,
                tuple(params + [limit, offset]),
            )
            total = fetch_one(
                f"""
                SELECT COUNT(*) AS total
                FROM optimization_history o
                LEFT JOIN clients c ON c.client_id = o.client_id
                {where}
                """,
                tuple(params),
            ) or {}
            return {"items": [action_item(row) for row in rows], "total": int(total.get("total") or 0), "limit": limit, "offset": offset, "source": "database"}
        except Exception:
            pass
    items = filter_mock_actions(filters)
    sort_by = filters.get("sort_by") or "created_at"
    reverse = str(filters.get("sort_dir") or "desc").lower() != "asc"
    items.sort(key=lambda item: sort_value(item.get(sort_by)), reverse=reverse)
    return {"items": items[offset : offset + limit], "total": len(items), "limit": limit, "offset": offset, "source": "mock"}


def sort_value(value: Any) -> tuple[int, Any]:
    if value is None:
        return (1, "")
    return (0, value)


def filter_mock_actions(filters: dict[str, Any]) -> list[dict[str, Any]]:
    items = mock_action_rows()
    for key, field in [("client_id", "client_id"), ("platform", "target_platform"), ("risk_level", "risk_level"), ("status", "status"), ("agent_name", "agent_name")]:
        if filters.get(key):
            items = [item for item in items if item.get(field) == filters[key]]
    if filters.get("rollback_flag") is not None:
        items = [item for item in items if item["rollback_flag"] is bool(filters["rollback_flag"])]
    if filters.get("search"):
        search = str(filters["search"]).lower()
        items = [
            item for item in items
            if search in " ".join(str(item.get(key, "")) for key in ("action_type", "reason", "brand_name", "target_platform", "target_campaign_id", "agent_name", "approved_by")).lower()
        ]
    return items


def get_facets() -> dict[str, Any]:
    if is_db_configured():
        try:
            return {
                "clients": fetch_all("SELECT client_id, brand_name FROM clients ORDER BY brand_name"),
                "platforms": [row["target_platform"] for row in fetch_all("SELECT DISTINCT target_platform FROM optimization_history WHERE target_platform IS NOT NULL ORDER BY target_platform")],
                "risk_levels": [row["risk_level"] for row in fetch_all("SELECT DISTINCT risk_level FROM optimization_history WHERE risk_level IS NOT NULL ORDER BY risk_level")],
                "statuses": [row["status"] for row in fetch_all("SELECT DISTINCT status FROM optimization_history WHERE status IS NOT NULL ORDER BY status")],
                "agents": [row["agent_name"] for row in fetch_all("SELECT DISTINCT agent_name FROM optimization_history WHERE agent_name IS NOT NULL ORDER BY agent_name")],
                "source": "database",
            }
        except Exception:
            pass
    items = mock_action_rows()
    return {
        "clients": [{"client_id": item["client_id"], "brand_name": item["brand_name"]} for item in items],
        "platforms": sorted({item["target_platform"] for item in items} | {"Meta", "Google"}),
        "risk_levels": ["Low", "Medium", "High"],
        "statuses": SUMMARY_STATUSES,
        "agents": sorted({item["agent_name"] for item in items} | set(DEFAULT_AGENTS)),
        "source": "mock",
    }


def get_action_detail(optimization_id: str) -> dict[str, Any]:
    action = get_action_or_404(optimization_id)
    client: dict[str, Any] = {}
    campaign: dict[str, Any] = {}
    related_recommendation = None
    if is_db_configured():
        try:
            client = fetch_one("SELECT * FROM clients WHERE client_id = %s", (action["client_id"],)) or {}
            if action.get("target_campaign_id"):
                campaign = fetch_one("SELECT * FROM ad_campaign_settings WHERE campaign_id = %s", (action["target_campaign_id"],)) or {}
            related_recommendation = infer_recommendation(action)
        except Exception:
            client = {}
            campaign = {}
    events = get_audit_events({"action_id": optimization_id, "limit": 100})["items"]
    return {
        "action": action,
        "client": client or {"client_id": action["client_id"], "brand_name": action["brand_name"], "brand_category": action.get("brand_category")},
        "campaign": campaign or {"campaign_id": action.get("target_campaign_id"), "campaign_name": action.get("campaign_name"), "platform": action.get("target_platform")},
        "related_recommendation": related_recommendation,
        "audit_events": events,
        "rollback_plan": rollback_plan(action),
        "safety_checks": safety_checks(action),
        "source": "database" if is_db_configured() else "mock",
    }


def get_action_or_404(optimization_id: str) -> dict[str, Any]:
    if is_db_configured():
        try:
            row = fetch_one(
                """
                SELECT o.*, c.brand_name, c.brand_category, s.campaign_name
                FROM optimization_history o
                LEFT JOIN clients c ON c.client_id = o.client_id
                LEFT JOIN ad_campaign_settings s ON s.campaign_id = o.target_campaign_id
                WHERE o.optimization_id = %s
                """,
                (optimization_id,),
            )
            if row:
                return action_item(row)
        except Exception:
            pass
    action = next((item for item in mock_action_rows() if item["optimization_id"] == optimization_id), None)
    if not action:
        raise HTTPException(status_code=404, detail="Optimization action not found")
    return action


def infer_recommendation(action: dict[str, Any]) -> Optional[dict[str, Any]]:
    if not is_db_configured():
        return None
    return fetch_one(
        """
        SELECT *
        FROM recommendation_records
        WHERE client_id = %s
          AND (
            target_campaign_id = %s
            OR lower(recommendation_type) = lower(%s)
            OR lower(target_platform) = lower(%s)
          )
        ORDER BY ABS(EXTRACT(EPOCH FROM (detected_at - %s::timestamptz))) ASC
        LIMIT 1
        """,
        (
            action["client_id"],
            action.get("target_campaign_id"),
            action.get("action_type"),
            action.get("target_platform"),
            action.get("created_at"),
        ),
    )


def rollback_plan(action_or_id: dict[str, Any] | str) -> dict[str, Any]:
    action = action_or_id if isinstance(action_or_id, dict) else get_action_or_404(action_or_id)
    status = action["status"]
    eligible = status in {"Executed", "Approved"}
    blocking_reason = None
    if status in {"Generated", "Pending Review"}:
        blocking_reason = "Action has not been executed yet; rollback is not needed."
    elif status == "Rejected":
        blocking_reason = "Rejected actions are not eligible for rollback."
    elif status == "Rolled Back":
        blocking_reason = "Action has already been rolled back."
    return {
        "rollback_available": eligible,
        "rollback_type": "restore_previous_campaign_or_audience_configuration",
        "summary": "Restore the prior campaign/audience state using the audit log and previous optimization state.",
        "steps": [
            "Confirm current optimization is underperforming against guardrail thresholds.",
            "Retrieve previous configuration snapshot or prior known-good state.",
            "Revert audience/campaign setting in the ad platform.",
            "Monitor CPA, ROAS, spend, and purchases for the next 24-72 hours.",
            "Record rollback outcome in optimization history and agent logs.",
        ],
        "rollback_eligibility": "eligible" if eligible else "not_eligible",
        "blocking_reason": blocking_reason,
    }


def safety_checks(action: dict[str, Any]) -> list[dict[str, Any]]:
    return [
        {"label": "External API calls disabled", "status": "passed", "message": "Demo execution never calls Meta or Google Ads APIs."},
        {"label": "Rollback plan available", "status": "passed" if action["status"] in {"Approved", "Executed", "Rolled Back"} else "pending", "message": "A conceptual rollback path is attached before execution."},
        {"label": "High-risk approval gate", "status": "passed" if action["risk_level"] != "High" or action.get("approved_by") else "blocked", "message": "High-risk changes require human approval."},
        {"label": "Evidence references attached", "status": "passed" if action.get("evidence_refs") else "pending", "message": "Evidence refs support auditability without exposing hidden reasoning."},
    ]


def get_audit_events(filters: dict[str, Any]) -> dict[str, Any]:
    limit = int(filters.get("limit") or 100)
    if is_db_configured():
        try:
            clauses = []
            params: list[Any] = []
            for key in ("action_id", "recommendation_id", "client_id"):
                if filters.get(key):
                    clauses.append(f"{key} = %s")
                    params.append(filters[key])
            where = f"WHERE {' AND '.join(clauses)}" if clauses else ""
            rows = fetch_all(
                f"""
                SELECT audit_id, action_id, recommendation_id, client_id, event_type, event_status, actor, message, metadata, created_at
                FROM action_audit_events
                {where}
                ORDER BY created_at DESC
                LIMIT %s
                """,
                tuple(params + [limit]),
            )
            return {"items": [audit_event(row) for row in rows], "source": "database"}
        except Exception:
            pass
    events = [audit_event(row) for row in _fallback_events]
    for key in ("action_id", "recommendation_id", "client_id"):
        if filters.get(key):
            events = [event for event in events if event.get(key) == filters[key]]
    return {"items": events[:limit], "source": "mock"}


def audit_event(row: dict[str, Any]) -> dict[str, Any]:
    return {
        "audit_id": row.get("audit_id") or f"audit-{uuid.uuid4().hex[:10]}",
        "action_id": row.get("action_id"),
        "recommendation_id": row.get("recommendation_id"),
        "client_id": row.get("client_id"),
        "event_type": row.get("event_type"),
        "event_status": row.get("event_status"),
        "actor": row.get("actor"),
        "message": row.get("message"),
        "metadata": parse_json(row.get("metadata"), {}),
        "created_at": iso(row.get("created_at")) or now_iso(),
    }


def simulate_execution(optimization_id: str, payload: dict[str, Any]) -> dict[str, Any]:
    action = get_action_or_404(optimization_id)
    if action["status"] in {"Rejected", "Rolled Back"}:
        raise HTTPException(status_code=400, detail=f"Cannot simulate execution for {action['status']} action.")
    if action["status"] not in {"Generated", "Approved", "Pending Review"}:
        raise HTTPException(status_code=400, detail="Only generated, approved, or pending review actions can be simulated for execution.")
    guardrail_block = execution_blocking_reason(action)
    if guardrail_block:
        raise HTTPException(status_code=400, detail=guardrail_block)
    actor = payload.get("executed_by") or "human_ops"
    note = payload.get("note") or "Simulated execution for demo."
    update_action_status(action, "Executed", False)
    event = create_audit_event(action, "execution_simulated", "completed", actor, note)
    create_agent_log(
        "Action Executor",
        f"Simulated execution completed for optimization {optimization_id}. No external ad platform API was called.",
        "success",
        related_entity_type="optimization",
        related_entity_id=optimization_id,
    )
    updated = get_action_or_404(optimization_id)
    return {"action": updated, "audit_event": event, "source": "database" if is_db_configured() else "mock"}


def execution_blocking_reason(action: dict[str, Any]) -> str | None:
    settings = get_guardrails()
    if settings.get("rollback_required_for_execution") and action["status"] not in {"Approved"} and action["risk_level"] == "High":
        return "High-risk actions require approval and rollback readiness before simulated execution."
    if action["risk_level"] == "High" and settings.get("high_risk_requires_approval") and not action.get("approved_by"):
        return "High-risk actions require human approval before simulated execution."
    if action["risk_level"] == "Medium" and settings.get("medium_risk_requires_approval") and not action.get("approved_by"):
        return "Medium-risk actions require human approval before simulated execution."
    text = f"{action.get('action_type', '')} {action.get('reason', '')}".lower()
    if settings.get("budget_changes_require_approval") and any(term in text for term in ("budget", "bid")) and not action.get("approved_by"):
        return "Budget or bid changes require human approval before simulated execution."
    if settings.get("campaign_pause_requires_approval") and any(term in text for term in ("pause", "campaign")) and not action.get("approved_by"):
        return "Campaign pause changes require human approval before simulated execution."
    return None


def simulate_rollback(optimization_id: str, payload: dict[str, Any]) -> dict[str, Any]:
    action = get_action_or_404(optimization_id)
    if action["status"] not in {"Executed", "Approved"}:
        raise HTTPException(status_code=400, detail="Only executed or approved actions are eligible for simulated rollback.")
    actor = payload.get("rolled_back_by") or "human_ops"
    reason = payload.get("reason") or "Simulated rollback for demo."
    update_action_status(action, "Rolled Back", True)
    event = create_audit_event(action, "rollback_completed", "completed", actor, reason)
    create_agent_log(
        "Action Executor",
        f"Simulated rollback completed for optimization {optimization_id}.",
        "warning",
        related_entity_type="optimization",
        related_entity_id=optimization_id,
    )
    updated = get_action_or_404(optimization_id)
    return {"action": updated, "audit_event": event, "source": "database" if is_db_configured() else "mock"}


def update_action_status(action: dict[str, Any], status: str, rollback_flag: bool) -> None:
    if is_db_configured():
        try:
            with get_db_connection() as conn:
                conn.execute(
                    """
                    UPDATE optimization_history
                    SET status = %s, rollback_flag = %s
                    WHERE optimization_id = %s
                    """,
                    (status, rollback_flag, action["optimization_id"]),
                )
            return
        except Exception:
            pass
    for item in _fallback_actions:
        if item.get("id") == action["optimization_id"] or item.get("optimization_id") == action["optimization_id"]:
            item["status"] = status
            item["rollback_flag"] = rollback_flag
            item["rollback_status"] = "rolled_back" if rollback_flag else item.get("rollback_status", "not_needed")
            item["actual_impact_pct"] = item.get("actual_impact_pct", action.get("expected_impact_pct", 0.08) * 0.75)


def create_audit_event(action: dict[str, Any], event_type: str, event_status: str, actor: str, message: str) -> dict[str, Any]:
    event = {
        "audit_id": f"AUD_{uuid.uuid4().hex[:12]}",
        "action_id": action["optimization_id"],
        "recommendation_id": action.get("recommendation_id"),
        "client_id": action.get("client_id"),
        "event_type": event_type,
        "event_status": event_status,
        "actor": actor,
        "message": message,
        "metadata": {"simulated": True, "external_api_called": False},
        "created_at": now_iso(),
    }
    _fallback_events.insert(0, event)
    if is_db_configured():
        try:
            with get_db_connection() as conn:
                conn.execute(
                    """
                    INSERT INTO action_audit_events (
                        audit_id, action_id, recommendation_id, client_id, event_type,
                        event_status, actor, message, metadata, created_at
                    )
                    VALUES (%s, %s, %s, %s, %s, %s, %s, %s, %s::jsonb, now())
                    """,
                    (
                        event["audit_id"], event["action_id"], event["recommendation_id"], event["client_id"],
                        event["event_type"], event["event_status"], event["actor"], event["message"],
                        json.dumps(event["metadata"]),
                    ),
                )
        except Exception:
            pass
    return event
